export const Constants = {
    getAllClient: 'api/Client/GetClientList',
    addClientDetails: 'api/Client/AddClientPrimaryInfo',
    deleteClientDetails: 'api/Client/DeleteClientListing',
    AddPrimaryCareInfo: 'api/Client/AddClientPrimaryCareInfo',
    AddClientOnBoardingNotes: 'api/Client/AddClientBoardingNotes',
    AddClientAdditionalNotes: 'api/Client/AddClientAdditionalNotes',
    AddClientFundingInfo:'api/Client/AddClientFundingInfo',
    AddClientFundingTypeInfo:'api/Client/AddClientFunding',
    EditClientFundingTypeInfo:'api/Client/UpdateClientFunding',
    DeleteClientFundingTypeInfo:'api/Client/DeleteClientFunding',
    GetClientFundingList:'api/Client/GetClientFundingtypeList',
    UpdateClientBasicInfo:'api/Client/UpdateClientPrimaryInfo',
    GetClientDetailPageInfo:'api/Client/GetClientDetails',
    GetAllClientMedicalHistory:'api/Client/GetAllClientMedicalHistory',
    deleteClientMedicalhistory: 'api/Client/DeleteClientMedicalHistory',
    GetClientPrimaryInfo:'api/Client/GetClientPrimaryInfo',
    AddClientMedicalHistory:'api/Client/AddClientMedicalHistory',
    AddClientProgressNote:'api/Client/AddClientProgressNotes',
    AddClientProgressNoteItem:'api/Client/AddClientProgressNotesItem',
    UpdateClientProgressNoteItem:'api/Client/UpdateClientProgressNotesItem',
    GetClientProgressNote:'api/Client/GetClientProgressNotes',
    GetClientProgressNoteItem:'api/Client/GetClientProgressNotesList',
    GetAllClientProgressNotes:'api/Client/GetAllClientProgressNotes',
    DeleteClientProgressNotes: 'api/Client/DeleteClientProgressNotes',
    GetClientProgressSingleNote: 'api/Client/GetClientProgressSingleNote',
    DeleteClientProgressNotesItem: 'api/Client/DeleteClientProgressNotesItem',
    GetClientMedicalHistoryDetails: 'api/Client/GetClientMedicalDetails',
    AddClientSuppportCoordinator: 'api/Client/AddClientSupportCoordinator',
    AddClientCompliancesInfo: 'api/Client/AddClientCompliancesInfo',
    GetClientCompliancesList: 'api/Client/GetClientCompliancesList',
    UpdateClientCompliancesInfo: 'api/Client/UpdateClientCompliancesInfo',
    DeleteClientComplianceInfo: 'api/Client/DeleteClientComplianceInfo',
    GetClientAlldocumentList: 'api/Client/GetAllClientDocumentsList',
    DeleteClientDocument: 'api/Client/DeleteClientDocument',
    BaseURL: 'http://localhost:62431/', //http://52.25.96.244:7031/,
    AddClientAccidentIncidentInfo: 'api/Client/AddClientAccidentIncidentInfo',
    GetClientAccidentIncidentList: 'api/Client/GetClientAccidentIncidentList',
    UpdateClientAccidentIncident: 'api/Client/UpdateClientAccidentInfo',
    DeleteClientAccidentIncident: 'api/Client/DeleteClientAccidentInfo',
    GetAllClientAccidentList: 'api/Client/GetAllClientAccidentList',
    UpdateClientProfileImage: 'api/Client/AddClientPicInfo',
    GetClientAccidentDetails: 'api/Client/GetClientAccidentDetails',
    GetClientCompliancesDetails: 'api/Client/GetClientCompliancesDetails',
    GetClientMedicalDetails: 'api/Client/GetClientMedicalInfo',
    GetProgressNotesDetails: 'api/Client/GetProgressNotesDetails',
    AddGuardianInfo: 'api/Client/AddGuardianInfo',
    GetClientContactOtherPerson: 'api/Client/GetOtherContactPerson',
    DeleteClientContactOtherPerson: 'api/Client/DeleteClientContactOtherPerson',
    UpdateActiveClientStatus: 'api/Client/UpdateClientActiveStatus',
    AddClientCultureNeedInfo: 'api/Client/AddClientCultureNeed',
    AddClientBehaviourConcernInfo: 'api/Client/AddClientBehaviourConcern',
    AddClientEatingNutritionInfo: 'api/Client/AddClientEatingNutrition',
    AddClientLivingArrangementInfo: 'api/Client/AddClientLivingArrangement',
    AddClientOtherInformtionInfo: 'api/Client/AddClientOtherInformtion',
    AddClientSocialConnectionsInfo: 'api/Client/AddClientSocialConnections',
    AddClientPreferencesInfo: 'api/Client/AddClientPreferences',
    getClientProfileDetails: 'api/Client/GetClientProfileDetails',
    AddClientIncidentCategory: 'api/Client/AddIncidentCategory',
    AddIncidentDeclaration: 'api/Client/AddIncidentDeclaration',
    AddIncidentDetails: 'api/Client/AddIncidentDetails',
    AddIncidentDocuments: 'api/Client/AddIncidentDocuments',
    AddIncidentImmediateAction: 'api/Client/AddIncidentImmediateAction',
    AddIncidentImpactedPerson: 'api/Client/AddIncidentImpactedPerson',
    AddIncidentContactInfo: 'api/Client/AddIncidentPrimaryContact',
    AddIncidentProviderdetail: 'api/Client/AddIncidentProviderDetail',
    AddIncidentRiskAssesment: 'api/Client/AddIncidentRiskAssesment',
    AddIncidentSubjectAllegation: 'api/Client/AddInciidentSubjectAllegation',
    UpdateIncidentSubjectAllegation: 'api/Client/UpdateIncidentSubjectAllegation',
    GetAllIncidentDetails: 'api/Client/GetIncidentDetails',
    UpdateIncidentDocuments: 'api/Client/UpdateIncidentDocument',
    DeleteIncidentDocument: 'api/Client/DeleteIncidentDocument',
    GetIncidentDocumentDetail: 'api/Client/GetIncidentDocumentDetail',
    GetIncidentImpactedPerson: 'api/Client/GetIncidentImpactedPerson',
    GetIncidentSubjectAllegation: 'api/Client/GetIncidentSubjectAllegation',
    GetClientIncidentCategory: 'api/Client/GetClientIncidentCategory',
    getAccidentIncidentInfo: 'api/Client/GetAccidentIncidentInfo',
    generateUserandPass: 'api/Client/GenerateUserAndPassword',
    getClientShitList: 'api/Client/GetClientShiftList',
    getRiskAssesment: 'api/Client/GetRiskAssesment',
    deleteClientAgreement: 'api/Client/DeleteClientAgreement',
    getClientAgreementInfo: 'api/Client/GetClientAgreementInfo',
}
