export const Constants = {
    getAllLocation: 'api/Administration/GetLocationList',
    addLocationDetails: 'api/Administration/AddLocation',
    updateEmployeeJobProfile: 'api/Employee/AddEmployeeJobProfile',
    getLocationDetailById: 'api/Administration/GetLocationDetail',
    UpdateLocationDetails: 'api/Administration/EditLocationInfo',
    DeleteLocation: 'api/Administration/DeleteLocationInfo',
    AddMasterEntries: 'api/Administration/AddMasterEntries',
    UpdateMasterEntries: 'api/Administration/EditMasterEntries',
    UpdateMasterActiveStatus: 'api/Administration/UpdateMasterActiveInActive',
    GetAllMasterEntries: 'api/Administration/GetAllMasterEntries',
    AddPublicHoliday: 'api/Administration/AddPublicHoliday',
    DeletePublicHoliday: 'api/Administration/DeletePublicHoliday',
    UpdatePublicHoliday: 'api/Administration/UpdatePublicHoliday',
    GetAllPublicHoliday: 'api/Administration/GetAllPublicHoliday',
    AddToDolistItem: 'api/Administration/AddToDoListItem',
    DeleteToDolistItem: 'api/Administration/DeleteToDoItem',
    UpdateToDolistItem: 'api/Administration/UpdateToDoListItem',
    GetShiftItem:'api/Administration/GetToDoItems',
    getShifttype:'api/Master/GetShiftTime',
    getUserActivitylog:'api/Administration/GetUserAuditLog',
    getpayrateInfo:'api/Master/GetPayRateDetails',
    EditpayrateInfo:'api/Administration/EditPayRateDetails',
    Uploadserviceprice:'api/Administration/UploadServicePrice',
    GetServiceRate:'api/Administration/GetServiceRate',
    addLatLongLocationDetails: 'api/Administration/AddLatLongLocation',
    editLatLongLocationDetails: 'api/Administration/EditLatLongLocation',
};
