export const Constants = {
    dateFormat : 'dd MMM yyyy',
    getAllEmployee: 'api/Employee/GetEmployeeList',
    addEmployeeDetails: 'api/Employee/AddEmployeeInfo',
    getEmployeeDetails : 'api/Employee/GetEmployeeDetail',
    editEmployeeDetails: 'api/Employee/EditEmployeeInfo',
    updateEmployeeAwardDetails: 'api/Employee/AddEmployeeAwardInfo',
    updateEmployeeKinInfo: 'api/Employee/AddEmployeeKinInfo',
    updateLicenseInfo: 'api/Employee/AddEmployeeDrivingLicenseInfo',
    updateEmployeeJobProfile: 'api/Employee/AddEmployeeJobProfile',
    // updateLicenseInfo: 'api/Employee/AddEmployeeDrivingLicenseInfo',
    updateEducationInfo: 'api/Employee/AddEmployeeEducation',
    updatePayrate: 'api/Employee/AddEmployeePayRate',
    updateMiscInfo : 'api/Employee/AddEmployeeMiscInfo',
    updateWorkExperience: 'api/Employee/AddEmployeeWorkExp',
    getEmployeeAccidentIncident : 'api/Employee/GetAccidentIncidentList',
    updateEmployeeAccidentIncident : 'api/Employee/AddEmployeeAccidentInfo',
    getCommunicationInfo : 'api/Employee/GetEmployeeCommunicationList',
    addCommunicationInfo : 'api/Employee/AddEmployeeCommunicationInfo',
    getEmployeeLeaveList : 'api/Employee/GetLeaveList',
    AddEmpLeave : 'api/Employee/AddEmployeeLeaveDetail',
    UpdateEmpLeave : 'api/Employee/EditEmployeeLeaveInfo',
    getAllEmployeeCommunication : 'api/Employee/GetAllEmployeeCommunicationList',
    getAllEmployeeAccident: 'api/Employee/GetAllEmployeeAccidentList',
    addEmployeeStaffWarning: 'api/Employee/AddEmployeeStaffWarningDetail',
    getAllEmployeeAppraisalList: 'api/Employee/GetAllEmployeeAppraisalList',
    getRequireComplianceList: 'api/Employee/GetRequireCompliancesList',
    getOtherComplianceList: 'api/Employee/GetOtherComplianceDetails',
    getAllEmployeeLeaveList: 'api/Employee/GetAllEmployeeLeaveList',
    getAllEmployeestaffwarningList: 'api/Employee/GetAllEmployeeStafwarning',
    addEmployeeAppraisalInfo: 'api/Employee/AddEmployeeAppraisalDetail',
    addEmployeeCompliancesDetail: 'api/Employee/AddEmployeeCompliancesDetail',
    DeleteAccidentInfo: 'api/Employee/DeleteEmployeeAccidentInfo',
    DeleteAppraisalInfo: 'api/Employee/DeleteEmployeeAppraisalInfo',
    DeleteCommunicationInfo: 'api/Employee/DeleteEmployeeCommunication',
    DeleteLeaveInfo: 'api/Employee/DeleteEmployeeLeave',
    DeleteStaffInfo: 'api/Employee/DeleteEmployeeStaffWarning',
    DeleteRequireComplianceDetails: 'api/Employee/DeleteEmployeeCompliancesInfo',
    DeleteOtherComplianceDetails: 'api/Employee/DeleteEmployeeOtherCompliance',
    getEmployeestaffwarningList: 'api/Employee/GetStaffWarningList',
    UpdateEmployeeStaffWarning: 'api/Employee/EditEmployeeStaffWarningInfo',
    AddOtherComplianceDetails: 'api/Employee/AddEmployeeOtherCompliancesDetail',
    getOtherComplianceDetails: 'api/Employee/GetOtherCompliancesList',
    updateOtherComplianceDetails: 'api/Employee/EditEmployeeOtherCompliancesInfo',
    EditCommunicationInfo : 'api/Employee/EditEmployeeCommunicationInfo',
    updateEmployeeAccidentinfo : 'api/Employee/EditEmployeeAccidentInfo',
    getEmployeePrimaryInfo : 'api/Employee/GetEmployeePrimaryInfo',
    getEmployeeAppraisalList: 'api/Employee/GetAllAppraisalList',
    EditEmployeeCompliancesDetail: 'api/Employee/EditEmployeeCompliancesInfo',
    EditEmployeeAppraisalInfo: 'api/Employee/UpdateEmployeeAppraisalDetail',
    updateRmployeeProfileImage: 'api/Employee/AddEmployeePicInfo',
    BaseURL: 'http://localhost:62431/', //http://52.25.96.244:7031/,
    DeleteEmployeeRequireDocument: 'api/Employee/DeleteEmployeeRequireDocument',
    DeleteEmployeeOtherDocument: 'api/Employee/DeleteEmployeeOtherDocument',
    getAllRequireComplianceList: 'api/Employee/GetAllEmployeeReqComplianceList',
    getAllOtherComplianceList: 'api/Employee/GetAllEmployeeOthComplianceList',
    getCommunicationById : 'api/Employee/GetEmployeeCommunicationDetail',
    getLeaveById : 'api/Employee/GetEmployeeLeaveDetail',
    getaccidentById : 'api/Employee/GetEmployeeAccidentDetail',
    getRequiredataById : 'api/Employee/GetEmployeeCompliancesDetail',
    getotherdataById : 'api/Employee/GetOtherComplianceDetails',  
    getstaffwarningdataById : 'api/Employee/GetEmployeeStaffWarningDetail',
    GetEmployeeAppraisaldetails : 'api/Employee/GetEmployeeAppraisaldetails',
    DeleteEmployeedetails : 'api/Employee/DeleteEmployeedetails',
    DeleteEmployeeEducationdetails : 'api/Employee/DeleteEmployeeEducationdetails',
    DeleteEmployeeExperiencedetails:'api/Employee/DeleteEmployeeExperiencedetails',
    AddEmployeeTraining:'api/Employee/AddEmployeeTraningInfo',
    DeleteEmployeeTraining:'api/Employee/DeleteEmployeeTraining',
    UpdateEmployeeTraining:'api/Employee/UpdateEmployeeTraining',
    GetEmployeeTrainingList:'api/Employee/GetEmployeeTrainingList',
    GetEmployeeEducationList:'api/Employee/GetEmployeeEducationList',
    GetEmployeeExperienceList:'api/Employee/GetEmployeeExperienceList',
    DeleteEmployeeEducationDocument:'api/Employee/DeleteEmployeeEducationDocument',
    DeleteEmployeeExperienceDocument:'api/Employee/DeleteEmployeeExperienceDocument',
    DeleteEmployeeTrainingDocument:'api/Employee/DeleteTrainingDocument',
    UpdateActiveInActiveStatus:'api/Employee/UpdateEmployeeActiveStatus',
    GetEmployeeTodayShift:'api/Employee/GetEmployeeTodayShiftInfo',
    UpdateEmployeePassword:'api/Employee/UpdateEmployeePassword',
    getEmployeePassword:'api/Employee/GetEmployeePasswordInfo',
    GetEmployeeDriverList:'api/Employee/GetEmployeeDriverLicense',
    DeleteEmployeeDrivingLicense:'api/Employee/DeleteEmployeeDrivingLicense',
    ApproveLeaveById : 'api/Employee/ApproveEmployeeLeaveById',
    RejectLeaveById : 'api/Employee/RejectEmployeeLeaveById',
};
