export const Constants = {
    getAssignedShifts: 'api/EmployeeStaff/GetAssignedShifts',
    updateAcceptStatus: 'api/EmployeeStaff/UpdateAssignedAcceptStatus',
    updateRejectStatus: 'api/EmployeeStaff/UpdateAssignedRejectStatus',
    getCurrentShifts: 'api/EmployeeStaff/GetCurrentShifts',
    getShiftDetails: 'api/Shift/GetShiftInfo',
    addCheckInDetails: 'api/EmployeeStaff/SaveCurrentShiftInfo',    
    getEmployeeShiftList: 'api/EmployeeStaff/GetEmployeeShiftList',
    DeleteLeaveInfo: 'api/Employee/DeleteEmployeeLeave',
    getEmployeeLeaveList : 'api/Employee/GetLeaveList',
    AddEmpLeave : 'api/Employee/AddEmployeeLeaveDetail',
    UpdateEmpLeave : 'api/Employee/EditEmployeeLeaveInfo' ,  
    getEmployeeshifthours : 'api/EmployeeStaff/GetEmployeeShiftHours',   
    getEmployeeNotification : 'api/Notification/GetEmployeeNotification',   
    updateNotification: 'api/Notification/UpdateAdminNotification' ,  
    getApplyleave: 'api/EmployeeStaff/GetEmployeeApplyLeave'  , 
    updateLeaveApproveStatus: 'api/EmployeeStaff/UpdateLeaveApproveStatus' ,  
    updateLeaveRejectStatus: 'api/EmployeeStaff/UpdateLeaveRejectStatus',
    getClientUploadedDocument:'api/Client/GetClientCompliancesList' ,
    getShiftHistory:'api/Shift/GetShiftHistoryDetails'  
}
