export const Constants = {
    GetLanguage: 'api/Master/GetLanguage',
    getGenderList: 'api/Master/GetGender',
    getDepartmentList: 'api/Master/GetDepartment',
    getEmployeeType: 'api/Master/GetEmployeeType',
    getLevel: 'api/Master/GetLevel',
    getMaritalStatus: 'api/Master/GetMaritalStatus',
    getRelationship: 'api/Master/GetRelationship',
    getRoles: 'api/Master/GetRoles',
    getSalutation: 'api/Master/GetSalutation',
    getSourceOfHire: 'api/Master/GetSourceOfHire',
    getEventType: 'api/Master/GetEventType',
    getLocation: 'api/Master/GetLocation',
    getWarningType: 'api/Master/GetWarningType',
    getOffenseType: 'api/Master/GetOffenseType',
    getReportedTo: 'api/Master/GetReportedTo',
    getRaisedBy: 'api/Master/GetRaisedBy',
    getAppraisalType: 'api/Master/GetAppraisalType',
    GetAwardGroup :'api/Master/GetAwardGroup',
    GetGlobalPayRate :'api/Master/GetGlobalPayRate',
    getFundType: 'api/Master/GetFundType',
    getDocumentType: 'api/Master/GetDocumentType',
    getServiceType: 'api/Master/GetServiceType',
    GetAllClientNameList: 'api/client/GetAllClientNameList',
    getDocumentName: 'api/Master/GetDocumentName',
    getOtherDocumentName: 'api/Master/GetOtherDocumentName',
    getDepartmentbyemployee: 'api/Master/GetDepartmentByEmployee',
    getReportedbyemployee: 'api/Master/GetReportedByEmployee',
    getLeavetype: 'api/Master/GetLeaveType',
    getVisatype: 'api/Master/GetVisaType',
    getShiftStatusList : 'api/Master/GetShiftStatusList',
    getConditionType : 'api/Master/GetConditionType',
    getSymptomsType : 'api/Master/GetSymptomsType',
    getEthnicityType : 'api/Master/GetEthnicityType',
    getreligion : 'api/Master/GetReligion',
    getCountry : 'api/Master/GetCountry',
    getState : 'api/Master/GetState',
    getCourseype: 'api/Master/GetCourseType',
    getMandatoryTraining: 'api/Master/GetMandatoryTraining',
    getOptionalTraining: 'api/Master/GetOptionalTraining',
    getTrainingType: 'api/Master/GetTrainingType',
    getServiceList: 'api/Master/GetService',
    GetServiceRate :'api/Master/GetServiceRate',
    getLicenseType:'api/Master/GetLicenseType',
    getCodeType:'api/Master/GetCodeData',
    getLocationType:'api/Master/GetLocationType',
    getqualificationType:'api/Master/GetQualificationType',
    getHobbies:'api/Master/GetHobbies',
    getAppraisalCrieteria:'api/Master/GetAppraisalCrieteria',
    getTotalWarning:'api/Master/GetEmployeeTotalWarning',
    getPaymentterm:'api/Master/GetPaymentTerm',
    getPayers:'api/Master/GetPayers',
    getClientDocuments:'api/Master/GetClientDocuments',
    GetCommunicationType:'api/Master/GetCommunicationType',
    GetConcernBehaviour:'api/Master/GetConcernBehaviour',
    GetPrimaryCategory:'api/Master/GetPrimaryCategory',
    GetSecondaryCategory:'api/Master/GetSecondaryCategory',
    GetPrimaryDisability:'api/Master/GetPrimaryDisability',
    GetSecondaryDisability:'api/Master/GetSecondaryDisability',
    GetShiftTime:'api/Master/GetShiftTime',
    GetShiftItem:'api/Master/GetShiftItemList',
    GetPMShift:'api/Master/GetPMShift',
    GetActiveNightShift:'api/Master/GetActiveNightShift',
    GetEmployeeList:'api/Employee/GetAllEmployeeShortInfo',
    getOptionalDocument:'api/Master/GetClientOptionalDocument',
    getYear:'api/Master/getYear',
    GetCheckListDocument:'api/Master/GetCheckListDocument',
    getEmployeelevel:'api/Master/GetEmployeeLevel',
    getImageDetails:'api/Master/GetImageDetail',
    getdriverlicense:'api/Master/GetLicense',
    getcomplianceType:'api/Master/GetComplianceType',
    getReferenceNumber:'api/Master/GetReferenceNumber',
    GetEmpCheckListDocument:'api/Master/GetEmployeeCheckListdoc'
    
}



