export const Constants = {
    getEmployeeDetails : 'api/Employee/GetEmployeeDetail',
    editEmployeeDetails: 'api/Employee/EditEmployeeInfo',
    updateEmployeeAwardDetails: 'api/Employee/AddEmployeeAwardInfo',
    updateEmployeeKinInfo: 'api/Employee/AddEmployeeKinInfo',
    updateLicenseInfo: 'api/Employee/AddEmployeeDrivingLicenseInfo',
    updateEmployeeJobProfile: 'api/Employee/AddEmployeeJobProfile',
    updateEducationInfo: 'api/Employee/AddEmployeeEducation',
    updatePayrate: 'api/Employee/AddEmployeePayRate',
    updateWorkExperience: 'api/Employee/AddEmployeeWorkExp',
    getEmployeeAccidentIncident : 'api/Employee/GetAccidentIncidentList',
    updateEmployeeAccidentIncident : 'api/Employee/AddEmployeeAccidentInfo',
    getCommunicationInfo : 'api/Employee/GetEmployeeCommunicationList',
    addCommunicationInfo : 'api/Employee/AddEmployeeCommunicationInfo',
    getEmployeeLeaveList : 'api/Employee/GetLeaveList',
    AddEmpLeave : 'api/Employee/AddEmployeeLeaveDetail',
    UpdateEmpLeave : 'api/Employee/EditEmployeeLeaveInfo',
    addEmployeeStaffWarning: 'api/Employee/AddEmployeeStaffWarningDetail',
    getRequireComplianceList: 'api/Employee/GetRequireCompliancesList',
    getOtherComplianceList: 'api/Employee/GetOtherComplianceDetails',
    addEmployeeCompliancesDetail: 'api/Employee/AddEmployeeCompliancesDetail',
    DeleteAccidentInfo: 'api/Employee/DeleteEmployeeAccidentInfo',
    DeleteCommunicationInfo: 'api/Employee/DeleteEmployeeCommunication',
    DeleteLeaveInfo: 'api/Employee/DeleteEmployeeLeave',
    DeleteStaffInfo: 'api/Employee/DeleteEmployeeStaffWarning',
    DeleteRequireComplianceDetails: 'api/Employee/DeleteEmployeeCompliancesInfo',
    getEmployeestaffwarningList: 'api/Employee/GetStaffWarningList',
    UpdateEmployeeStaffWarning: 'api/Employee/EditEmployeeStaffWarningInfo',
    EditCommunicationInfo : 'api/Employee/EditEmployeeCommunicationInfo',
    updateEmployeeAccidentinfo : 'api/Employee/EditEmployeeAccidentInfo',
    getEmployeePrimaryInfo : 'api/Employee/GetEmployeePrimaryInfo',
    EditEmployeeCompliancesDetail: 'api/Employee/EditEmployeeCompliancesInfo',
    updateRmployeeProfileImage: 'api/Employee/AddEmployeePicInfo',
    DeleteEmployeeRequireDocument: 'api/Employee/DeleteEmployeeRequireDocument',
    DeleteEmployeedetails : 'api/Employee/DeleteEmployeedetails',
    DeleteEmployeeEducationdetails : 'api/Employee/DeleteEmployeeEducationdetails',
    DeleteEmployeeExperiencedetails:'api/Employee/DeleteEmployeeExperiencedetails',
    AddEmployeeTraining:'api/Employee/AddEmployeeTraningInfo',
    DeleteEmployeeTraining:'api/Employee/DeleteEmployeeTraining',
    UpdateEmployeeTraining:'api/Employee/UpdateEmployeeTraining',
    GetEmployeeTrainingList:'api/Employee/GetEmployeeTrainingList',
    GetEmployeeEducationList:'api/Employee/GetEmployeeEducationList',
    GetEmployeeExperienceList:'api/Employee/GetEmployeeExperienceList',
    DeleteEmployeeEducationDocument:'api/Employee/DeleteEmployeeEducationDocument',
    DeleteEmployeeExperienceDocument:'api/Employee/DeleteEmployeeExperienceDocument',
    DeleteEmployeeTrainingDocument:'api/Employee/DeleteTrainingDocument',
    UpdateActiveInActiveStatus:'api/Employee/UpdateEmployeeActiveStatus',
    GetEmployeeTodayShift:'api/Employee/GetEmployeeTodayShiftInfo',
    UpdateEmployeePassword:'api/Employee/UpdateEmployeePassword',
    getEmployeePassword:'api/Employee/GetEmployeePasswordInfo',
    GetEmployeeDriverList:'api/Employee/GetEmployeeDriverLicense',
    DeleteEmployeeDrivingLicense:'api/Employee/DeleteEmployeeDrivingLicense'
};
