export const Constants = {
    getEmployeeAccidentIncident: 'api/Employee/GetAccidentIncidentList',
    addEmployeeStaffWarning: 'api/Employee/AddEmployeeStaffWarningDetail',
    getEmployeestaffwarning: 'api/Employee/GetStaffWarningList',
    DeleteStaffInfo: 'api/Employee/DeleteEmployeeStaffWarning',
    UpdateEmployeeStaffWarning: 'api/Employee/EditEmployeeStaffWarningInfo',
    getCommunicationInfo : 'api/Employee/GetEmployeeCommunicationList',
    addCommunicationInfo : 'api/Employee/AddEmployeeCommunicationInfo',
    getComplianceList: 'api/Employee/GetRequireCompliancesList',
    editComplianceInfo: 'api/Employee/EditEmployeeCompliancesInfo',
    deleteComplianceDoc: 'api/Employee/DeleteEmployeeRequireDocument',
    deleteComplianceDetails: 'api/Employee/DeleteEmployeeCompliancesInfo',
    updateEmployeeAccidentinfo : 'api/Employee/EditEmployeeAccidentInfo',
    DeleteAccidentInfo: 'api/Employee/DeleteEmployeeAccidentInfo',
    updateEmployeeAccidentIncident : 'api/Employee/AddEmployeeAccidentInfo',
    addEmployeeCompliancesDetail: 'api/Employee/AddEmployeeCompliancesDetail',
    getEmployeeShiftList: 'api/EmployeeStaff/GetEmployeeShiftList',
    GetCheckOutClientList: 'api/EmployeeStaff/GetCheckOutClientList',
    GetAllIncidentDetails: 'api/Client/GetIncidentDetails',
}
